# NumPy for pandas

pandas is built atop NumPy and consequently one should learn about NumPy in the process of learning pandas.

# Installing and Importing NumPy

NumPy will have already been installed if pandas has been installed, so there's no need to worry about that.

In [1]:
# Import top-level NumPy functions using the np. prefix.
import numpy as np

## Benefits and Characteristics of NumPy Arrays

NumPy arrays are the bees knees when compared to ordinary Python lists. The nature of these benefits are primary performance and manipulation-oriented. Some benefits are outlined here:

* Continguous allocation in memory
* Vectorized operations
    * A technique for applying an operation across all or a subset of elements in an array. It's a hell of a lot faster than using for loops
* Boolean selection
    * Select elements from an array according to logical criteria.
* Sliceability
    * The ability to select elements in an array with a nice and tidy notation.

## Creating NumPy Arrays and Performing Basic Array Operations

There's more than one way to create a NumPy array.

In [2]:
# Create a basic array.
a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [3]:
# Show the array's type.
type(a1)

numpy.ndarray

In [4]:
# How many elements are there?
np.size(a1)

5

NumPy refers to n-dimensional arrays as `ndarray` and the one above comprises five elements, as reported by the `np.size()` function. Attempting to create an array with more than one data type prompts coercion.

In [5]:
# Mixed integers and floats results in float coercion.
a2 = np.array([1, 2, 3, 4.0, 5.0])
a2

array([ 1.,  2.,  3.,  4.,  5.])

In [8]:
# Examine the type of the array elements.
a2.dtype

dtype('float64')

There are more ways to create arrays.

In [9]:
a3 = np.array([0] * 10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create an array using the range() function.
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

An efficient means to create an array of zeros (sometimes useful) is to the `np.zeroes()` function.

In [12]:
# Create a numpy array of ten zeroes.
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

The `np.arange()` function is more effecient than passing 